### ISSUE TITLE
accuracy issue 

### ISSUE THREAD

**Issue by tyuuni** [cridemichel/QUARTICPP#2] opened 2024-01-03 08:34 UTC
**Failed case**
-40413.000000t^4 +0.000000t^3 -30266.000000t^2 +0.000000t +10147.000000 = 0
it gives:
r[0] = 0.611930i
r[1] = -0.611930i
r[2] = -0.611930i
r[3] = +0.611930i

i/-i should be two roots. (see below)
**In similar  cases it works just fine:**
-40414.000000t^4 +0.000000t^3 -30268.000000t^2 +0.000000t +10146.000000
it gives:
r[0] = 1.000000i
r[1] = -1.000000i
r[2] = -0.501051
r[3] = +0.501051

40415.000000t^4 +0.000000t^3 -30270.000000t^2 +0.000000t +10145.00000
it gives:
r[0] = 1.000000i
r[1] = -1.000000i
r[2] = -0.501020
r[3] = +0.501020

Using lib in this way:
quartic<long double, complex<long double>, true> Q;
pvector<long double, -1> coe(5);
pvector<complex<long double>, -1> r(4);
coe[4] = -40413;
coe[3] = 0;
coe[2] = -30266;
coe[1] = 0;
coe[0] = 10147;
Q.set_coeff(coe);
Q.find_roots(r);

**Comment by cridemichel** [comment] 2024-01-03 08:36
Dear  tyuuni,
thank you for the feedback, 
I will investigate the issue 
and I will report you back,

best regards
Cristiano


Cristiano De Michele
***@***.***

**Comment by cridemichel** [comment] 2024-01-03 09:01
Dear tyuuni,
unfortunately, I can not reproduce your issue.
First of all your code does not compile, since
"complex" is a template class in the STL and you
should specify the data type (float, double, long double).
In your code “complex” is an alias? 
If I use the following code: 

#include"./quartic.hpp"
int main(void)
{
  quartic<long double,complex<long double>,true> Q;
  pvector<long double,-1> c(5);
  pvector<complex<long double>,-1> r(4);
  c << 10147.0, 0.0, -30266.0, 0.0, -40413.0; 
  Q.set_coeff(c);
 
  Q.find_roots(r);
  r.show("roots");
  int cc=0;
  for (auto& r0: r)
    {
      cout << setprecision(16) << "root #" << cc <<  "=" << r0 << "\n";
      cout << setprecision(16) << "p(#" << cc << ")=" << Q.evalpoly(r0) << "\n\n";
      cc++;
    }

  return 0;
}

I get:

> ./quartic

roots{(0,1),(0,-1),(-0.5010814030070977671306453604672,0),(0.5010814030070977671306453604672,0)}
root #0=(0,1)
p(#0)=(0,0)

root #1=(0,-1)
p(#1)=(0,0)

root #2=(-0.5010814030070978,0)
p(#2)=(0,0)

root #3=(0.5010814030070978,0)
p(#3)=(0,0)

which are correct,

Similarly, if I employ double, i.e.:

#include"./quartic.hpp"
int main(void)
{
  quartic<double,complex<double>,true> Q;
  pvector<double,-1> c(5);
  pvector<complex<double>,-1> r(4);
  c << 10147.0, 0.0, -30266.0, 0.0, -40413.0; 
  Q.set_coeff(c);
 
  Q.find_roots(r);
  r.show("roots");
  int cc=0;
  for (auto& r0: r)
    {
      cout << setprecision(16) << "root #" << cc <<  "=" << r0 << "\n";
      cout << setprecision(16) << "p(#" << cc << ")=" << Q.evalpoly(r0) << "\n\n";
      cc++;
    }

  return 0;
}

I correctly obtain:

> ./quartic
roots{(0,1),(0,-1),(-0.5010814030070976921038550244702,0),(0.5010814030070978031261574869859,0)}
root #0=(0,1)
p(#0)=(5.551115123125783e-17,0)

root #1=(0,-1)
p(#1)=(5.551115123125783e-17,0)

root #2=(-0.5010814030070977,0)
p(#2)=(-1.110223024625157e-16,0)

root #3=(0.5010814030070978,0)
p(#3)=(5.551115123125783e-17,0)

best Cristiano

Cristiano De Michele
***@***.***

**Comment by tyuuni** [comment] 2024-01-03 10:24
Dear Cristiano,
Thank you for a quick reply.

Missing of data type after complex might be due to markdown, I just pasted code in the textbox. Anyway, it's not the point.

I found an interesting result.
When double is used, roots can be calculated correctly:
```
roots{(0,1),(0,-1),(-0.5010814030070976921038550244702,0),(0.5010814030070978031261574869859,0)}
```
When long double is used(using the exact code below), it still gives the wrong answer.
```
roots{(-0,0.6119303175842226248507850494551),(-0,-0.6119303175842226248507850494551),(0,-0.6119303179134948788447413703384),(0,0.6119303179134948788447413703384)}
```

I'm using Cmake to compile my project on Linux Mint 21.2 `Linux 5.15.0-91-generic #101-Ubuntu SMP Tue Nov 14 13:30:08 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux`.
I suspect this has something to do with Cmake.


_Code_
```
int main(int argc, char **argv) {
    quartic<long double, std::complex<long double>, true> Q;
    pvector<long double, -1> coe(5);
    pvector<std::complex<long double>, -1> r(4);
    coe[4] = -40413;
    coe[3] = 0;
    coe[2] = -30266;
    coe[1] = 0;
    coe[0] = 10147;
    Q.set_coeff(coe);
    Q.find_roots(r);
    r.show("roots");
}
```

**Comment by tyuuni** [comment] 2024-01-03 10:26
Perhaps this issue can be closed now.
If I can find anything further, I'll drop a comment.

**Comment by cridemichel** [comment] 2024-01-03 10:42
Dear Tyuuni,
I do not think it has to do with usage of "long double” or
with cmake either.
Indeed, I compiled your exact code, i.e.

#include"./quartic.hpp"
int main(void)
{
    quartic<long double, std::complex<long double>, true> Q;
    pvector<long double, -1> coe(5);
    pvector<std::complex<long double>, -1> r(4);
    coe[4] = -40413;
    coe[3] = 0;
    coe[2] = -30266;
    coe[1] = 0;
    coe[0] = 10147;
    Q.set_coeff(coe);
    Q.find_roots(r);
    r.show("roots");
    return 0;
}

and I get correctly:

❯ ./quartic

roots{(0,1),(0,-1),(-0.5010814030070977671306453604672,0),(0.5010814030070977671306453604672,0)}

Note that I both tried with clang  (Homebrew clang version 17.0.6, Target: x86_64-apple-darwin23.2.0)
and GNU gcc 13.2.0.
Were you using up-to-date version of my solver? I am asking since I applied a fix in 2022, without which
the wrong behavior you reported could be observed,

best C.
 
Cristiano De Michele
***@***.***

**Comment by cridemichel** [comment] 2024-01-03 14:54
Dear tyuuni,
I was able to reproduce the issue: in lubuntu (bookworm/sid), as you noticed, if long double are used,
roots are wrongly calculated. I attempted already to fix this problem (see #1), but, as it turned out, the fix 
required a refinement . Now, I hope the problem is definitely fixed, please check out latest version and 
let me know if everything is ok,

best C.

**Comment by tyuuni** [comment] 2024-01-04 03:07
Dear Cristiano,

Here's list of my tool.
```
Linux Mint 21.2 (I think it's based on Ubuntu 22.04)
Cmake 3.27.1
gcc version 11.4.0
target x86_64-linux-gnu
```

I tried the latest version. It now can solve the first case but failed the following:
`-32906.000000t^4 +0.000000t^3 -15252.000000t^2 +0.000000t +17654.000000 = 0`
it gives
```
roots{(-0,0.4814052848315963640786832589136),(-0,-0.4814052848315963640786832589136),(0,-0.4814052851997339356124316900321),(0,0.4814052851997339356124316900321)}
```
±i should be two roots.

try this:
```
int main(int argc, char **argv) {
    quartic<long double, complex<long double>, true> Q;
    pvector<long double, -1> coe(5);
    pvector<complex<long double>, -1> r(4);
    coe[4] = -32906;
    coe[3] = 0;
    coe[2] = -15252;
    coe[1] = 0;
    coe[0] = 17654;
    Q.set_coeff(coe);
    Q.find_roots(r);
    r.show("roots");
}
```

**Comment by cridemichel** [comment] 2024-01-04 09:53
Dear tyuuni,
I have just committed a new version,
which should definitely fix this issue. 
Please do all the tests you can do and let me know
if now it is working as expected,

thank you very much for your precious feedback,
Cristiano

**Comment by tyuuni** [comment] 2024-01-05 05:41
Dear Cristiano,

Thanks for the update!

It now passes all my current cases.

I'll continue testing for several days and report the result here.

**Comment by cridemichel** [comment] 2024-01-05 07:28
Dear Tyuuni,
I will wait for your report, 
before closing the issue.
Thank you very much!!

best C.

Cristiano De Michele
***@***.***

**Comment by cridemichel** [comment] 2024-01-06 20:55
Dear Tyuuni,
I committed an alternative fix which can be enabled as follows:
```C
#include"./quartic.hpp"
using dtype=long double;
int main(void)
{
  quartic<dtype,complex<dtype>,true> Q;
  pvector<dtype,-1> c(5);
  pvector<complex<dtype>,-1> r(4);
  // This is the Case 2 among accuracy tests in ACM Trans. Math. Softw. 46, 2, Article 20 (May 2020),
  // https://doi.org/10.1145/3386241
  c << 16.048044012,-32.072044006,24.036011,-8.006,1.0; 
  //c << 1.0,-17.678187643398402,-14.480985471938862,2.2459773428819827,1.0;
  // polynomial reported by tyuuni by github
  //c << 10147.0, 0.0, -30266.0, 0.0, -40413.0; 
  //c << 17654.0, 0.0, -15252.0, 0.0, -32906.0;
  Q.set_check_always_d20(true); // this command enables the alternative fix, 
  // if false it uses the fix which you already tested
  
  Q.set_coeff(c);
  Q.show("p(x)="); 
  Q.find_roots(r);
  r.show("roots");
  int cc=0;
  for (auto& r0: r)
    {
      cout << setprecision(16) << "root #" << cc <<  "=" << r0 << "\n";
      cout << setprecision(16) << "p(#" << cc << ")=" << Q.evalpoly(r0) << "\n\n";
      cc++;
    }

  return 0;
}
```
could you kindly test it against your polynomials?
best Cristiano

**Comment by cridemichel** [comment] 2024-01-11 15:05
Dear tyuuni,
any news? I would possibly like to close the issue….

best C.

Cristiano De Michele
***@***.***

**Comment by tyuuni** [comment] 2024-01-17 02:58
Dear Cristiano,
Sorry for late reply. I've been busy on other work these days but still did lots of tests. 

I'm using this lib to solve equations for determination of spacial positions where each use case generates at least thousands of similar equations like my posted cases. 
I tried many use cases and the update covers all these cases.

**Comment by cridemichel** [comment] 2024-01-17 05:41
Dear Tyuuni,
thank you very much for the feedback, did
you also test the latest version with the alternative
fix? If not, could you also do that please?

best regards, 
Cristiano

Cristiano De Michele
***@***.***

**Comment by tyuuni** [comment] 2024-01-18 07:48
Dear Cristiano,
Sure. It takes sometime since I didn't organize my use cases but just tested by manually changing values and recompiling.
I'll give new feedback by this weekend.

**Comment by cridemichel** [comment] 2024-01-18 07:51
you are very very kind!

Cristiano De Michele
***@***.***

**Comment by cridemichel** [comment] 2024-01-18 07:53
Dear tyuuni,
to test the the alternative fix do not forget to add the following instructions
```
Q.set_check_always_d20(true); 
```
before calling
```
Q.find_roots(...);
```
thanks again

**Comment by tyuuni** [comment] 2024-01-23 08:44
Dear Cristiano,
I've just finished a big refactoring of my codes, and will start test against it very heavily next two days.
So please wait for another couple of days.

**Comment by cridemichel** [comment] 2024-01-23 09:06
no enough words to say how much I thank you!

best C.

Cristiano De Michele
***@***.***

**Comment by tyuuni** [comment] 2024-01-24 10:06
so far so good. 
but I didn't see any difference.
it seems that all roots can be calculated no matter I call set_check_always_d20(true) or not.

is it that I didn't use the exact cases I used before? but still tens of thousands cases have been calculated this afternoon.

**Comment by cridemichel** [comment] 2024-01-24 11:52
thank very very much, 
I can close the issue then

best C.

Cristiano De Michele
***@***.***

**Closed as completed** 2024-01-24 16:56 UTC

**Comment by cridemichel** [comment] 2024-02-21 10:56
Dear tyuuni,
in your tests did you always consider polynomials of the form A x^4 + B x^2 + C, 
whose roots can be straightforwardly found by setting t=x^2 ?

best Cristiano
